/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v1_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/device/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Device Staff */
        get: operations["device_staff_api_v1_auth_device_staff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pin */
        post: operations["pin_api_v1_auth_pin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/device/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Device */
        post: operations["register_device_api_v1_auth_device_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/device/unregister": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unregister Device */
        post: operations["unregister_device_api_v1_auth_device_unregister_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Totp Setup */
        post: operations["totp_setup_api_v1_auth_totp_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Totp Enable */
        post: operations["totp_enable_api_v1_auth_totp_enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_v1_auth_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shop */
        get: operations["get_shop_api_v1_shop_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/shop/online-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Online Orders */
        patch: operations["online_orders_api_v1_staff_shop_online_orders_patch"];
        trace?: never;
    };
    "/api/v1/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_v1_admin_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["update_settings_api_v1_admin_settings_patch"];
        trace?: never;
    };
    "/api/v1/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Menu */
        get: operations["get_menu_api_v1_menu_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/menu/items/{item_id}/sold-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Item Sold Out */
        patch: operations["item_sold_out_api_v1_staff_menu_items__item_id__sold_out_patch"];
        trace?: never;
    };
    "/api/v1/staff/menu/options/{option_id}/sold-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Option Sold Out */
        patch: operations["option_sold_out_api_v1_staff_menu_options__option_id__sold_out_patch"];
        trace?: never;
    };
    "/api/v1/admin/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Admin Menu */
        get: operations["get_admin_menu_api_v1_admin_menu_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/menu/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Category */
        post: operations["create_category_api_v1_admin_menu_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/menu/categories/{cat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Category */
        delete: operations["delete_category_api_v1_admin_menu_categories__cat_id__delete"];
        options?: never;
        head?: never;
        /** Update Category */
        patch: operations["update_category_api_v1_admin_menu_categories__cat_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/menu/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Item */
        post: operations["create_item_api_v1_admin_menu_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/menu/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Item */
        delete: operations["delete_item_api_v1_admin_menu_items__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Item */
        patch: operations["update_item_api_v1_admin_menu_items__item_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/menu/items/{item_id}/option-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Item Groups */
        put: operations["set_item_groups_api_v1_admin_menu_items__item_id__option_groups_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/menu/items/{item_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Image */
        post: operations["upload_image_api_v1_admin_menu_items__item_id__image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/menu/option-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Group */
        post: operations["create_group_api_v1_admin_menu_option_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/menu/option-groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Group */
        delete: operations["delete_group_api_v1_admin_menu_option_groups__group_id__delete"];
        options?: never;
        head?: never;
        /** Update Group */
        patch: operations["update_group_api_v1_admin_menu_option_groups__group_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/menu/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Option */
        post: operations["create_option_api_v1_admin_menu_options_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/menu/options/{option_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Option */
        delete: operations["delete_option_api_v1_admin_menu_options__option_id__delete"];
        options?: never;
        head?: never;
        /** Update Option */
        patch: operations["update_option_api_v1_admin_menu_options__option_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/menu/sort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Sort */
        put: operations["sort_api_v1_admin_menu_sort_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quote */
        post: operations["quote_api_v1_orders_quote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Place Order */
        post: operations["place_order_api_v1_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/t/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Track */
        get: operations["track_api_v1_t__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/t/{token}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pay */
        post: operations["pay_api_v1_t__token__pay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/t/{token}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_v1_t__token__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Board
         * @description Active orders (placed, preparing, ready). Polled by the board; readable on a locked shop tablet.
         */
        get: operations["board_api_v1_staff_orders_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_staff_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/orders/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_staff_orders_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: operations["get_api_v1_staff_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/orders/{order_id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition */
        post: operations["transition_api_v1_staff_orders__order_id__transition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/orders/{order_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_v1_staff_orders__order_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{order_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_v1_admin_orders__order_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/orders/{order_id}/refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refund */
        post: operations["refund_api_v1_admin_orders__order_id__refund_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Staff */
        get: operations["list_staff_api_v1_admin_staff_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_admin_staff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/staff/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update */
        patch: operations["update_api_v1_admin_staff__user_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/staff/{user_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate */
        post: operations["deactivate_api_v1_admin_staff__user_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/staff/{user_id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reactivate */
        post: operations["reactivate_api_v1_admin_staff__user_id__reactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/staff/{user_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_v1_admin_staff__user_id__reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/staff/{user_id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Pin */
        post: operations["set_pin_api_v1_admin_staff__user_id__pin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/payments/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Payment Webhook
         * @description Verified by signature, not by session. Repeated deliveries are harmless.
         */
        post: operations["payment_webhook_api_v1_webhooks_payments__provider__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminCategory */
        AdminCategory: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Name Ms */
            name_ms: string | null;
            /** Sort Order */
            sort_order: number;
            /** Is Active */
            is_active: boolean;
        };
        /** AdminItem */
        AdminItem: {
            /** Id */
            id: number;
            /** Category Id */
            category_id: number;
            /** Name */
            name: string;
            /** Name Ms */
            name_ms: string | null;
            /** Description */
            description: string | null;
            /** Description Ms */
            description_ms: string | null;
            /** Price Sen */
            price_sen: number;
            /** Image Url */
            image_url: string | null;
            /** Sort Order */
            sort_order: number;
            /** Is Active */
            is_active: boolean;
            /** Is Sold Out */
            is_sold_out: boolean;
            /** Option Group Ids */
            option_group_ids: number[];
        };
        /** AdminMenuOut */
        AdminMenuOut: {
            /** Categories */
            categories: components["schemas"]["AdminCategory"][];
            /** Items */
            items: components["schemas"]["AdminItem"][];
            /** Option Groups */
            option_groups: components["schemas"]["AdminOptionGroup"][];
        };
        /** AdminOption */
        AdminOption: {
            /** Id */
            id: number;
            /** Option Group Id */
            option_group_id: number;
            /** Name */
            name: string;
            /** Name Ms */
            name_ms: string | null;
            /** Price Delta Sen */
            price_delta_sen: number;
            /** Sort Order */
            sort_order: number;
            /** Is Active */
            is_active: boolean;
            /** Is Sold Out */
            is_sold_out: boolean;
        };
        /** AdminOptionGroup */
        AdminOptionGroup: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Name Ms */
            name_ms: string | null;
            /** Min Select */
            min_select: number;
            /** Max Select */
            max_select: number;
            /** Is Active */
            is_active: boolean;
            /** Options */
            options: components["schemas"]["AdminOption"][];
        };
        /** Body_upload_image_api_v1_admin_menu_items__item_id__image_post */
        Body_upload_image_api_v1_admin_menu_items__item_id__image_post: {
            /** File */
            file: string;
        };
        /** CancelIn */
        CancelIn: {
            /** Version */
            version: number;
            /** Reason */
            reason: string;
            /** Refund Method */
            refund_method?: ("cash" | "original" | "later") | null;
        };
        /** CartLineIn */
        CartLineIn: {
            /** Menu Item Id */
            menu_item_id: number;
            /** Quantity */
            quantity: number;
            /** Option Ids */
            option_ids?: number[];
            /** Note */
            note?: string | null;
        };
        /** CategoryIn */
        CategoryIn: {
            /** Name */
            name: string;
            /** Name Ms */
            name_ms?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** CategoryPatch */
        CategoryPatch: {
            /** Name */
            name?: string | null;
            /** Name Ms */
            name_ms?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ChangePasswordIn */
        ChangePasswordIn: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** CounterOrderIn */
        CounterOrderIn: {
            /**
             * Channel
             * @default counter
             * @enum {string}
             */
            channel: "counter" | "phone";
            /** Customer Name */
            customer_name?: string | null;
            /** Note */
            note?: string | null;
            /** Items */
            items: components["schemas"]["CartLineIn"][];
            payment: components["schemas"]["CounterPaymentIn"];
            /** Expected Total Sen */
            expected_total_sen?: number | null;
        };
        /** CounterOrderOut */
        CounterOrderOut: {
            /** Id */
            id: number;
            /** Order Number */
            order_number: string;
            /** Order Code */
            order_code: string;
            /** Business Date */
            business_date: string;
            /** Channel */
            channel: string;
            /** Status */
            status: string;
            /** Payment Status */
            payment_status: string;
            /** Customer Name */
            customer_name: string | null;
            /** Note */
            note: string | null;
            /** Subtotal Sen */
            subtotal_sen: number;
            /** Total Sen */
            total_sen: number;
            /** Version */
            version: number;
            /** Auto Closed */
            auto_closed: boolean;
            /** Cancel Reason */
            cancel_reason: string | null;
            /** Created By Name */
            created_by_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Placed At */
            placed_at: string | null;
            /** Ready At */
            ready_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Cancelled At */
            cancelled_at: string | null;
            /** Items */
            items: components["schemas"]["OrderLine"][];
            /** Change Sen */
            change_sen: number | null;
        };
        /** CounterPaymentIn */
        CounterPaymentIn: {
            /**
             * Method
             * @enum {string}
             */
            method: "cash" | "qr_counter" | "card_terminal";
            /** Tendered Sen */
            tendered_sen?: number | null;
        };
        /** DeviceStaff */
        DeviceStaff: {
            /** Id */
            id: number;
            /** Full Name */
            full_name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ItemGroupsIn
         * @description The option groups attached to an item, in display order.
         */
        ItemGroupsIn: {
            /** Option Group Ids */
            option_group_ids: number[];
        };
        /** ItemIn */
        ItemIn: {
            /** Category Id */
            category_id: number;
            /** Name */
            name: string;
            /** Name Ms */
            name_ms?: string | null;
            /** Description */
            description?: string | null;
            /** Description Ms */
            description_ms?: string | null;
            /** Price Sen */
            price_sen: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** ItemPatch */
        ItemPatch: {
            /** Category Id */
            category_id?: number | null;
            /** Name */
            name?: string | null;
            /** Name Ms */
            name_ms?: string | null;
            /** Description */
            description?: string | null;
            /** Description Ms */
            description_ms?: string | null;
            /** Price Sen */
            price_sen?: number | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Is Sold Out */
            is_sold_out?: boolean | null;
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Login
             * @description Username or email
             */
            login: string;
            /** Password */
            password: string;
            /** Totp Code */
            totp_code?: string | null;
        };
        /** MenuCategoryOut */
        MenuCategoryOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Name Ms */
            name_ms: string | null;
            /** Items */
            items: components["schemas"]["MenuItemOut"][];
        };
        /** MenuGroupOut */
        MenuGroupOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Name Ms */
            name_ms: string | null;
            /** Min Select */
            min_select: number;
            /** Max Select */
            max_select: number;
            /** Options */
            options: components["schemas"]["MenuOptionOut"][];
        };
        /** MenuItemOut */
        MenuItemOut: {
            /** Id */
            id: number;
            /** Category Id */
            category_id: number;
            /** Name */
            name: string;
            /** Name Ms */
            name_ms: string | null;
            /** Description */
            description: string | null;
            /** Description Ms */
            description_ms: string | null;
            /** Price Sen */
            price_sen: number;
            /** Image Url */
            image_url: string | null;
            /** Image Url Large */
            image_url_large: string | null;
            /** Is Sold Out */
            is_sold_out: boolean;
            /** Item Sold Out */
            item_sold_out: boolean;
            /** Groups */
            groups: components["schemas"]["MenuGroupOut"][];
        };
        /** MenuOptionOut */
        MenuOptionOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Name Ms */
            name_ms: string | null;
            /** Price Delta Sen */
            price_delta_sen: number;
            /** Is Sold Out */
            is_sold_out: boolean;
        };
        /** MenuOut */
        MenuOut: {
            /** Categories */
            categories: components["schemas"]["MenuCategoryOut"][];
        };
        /** OnlineOrderIn */
        OnlineOrderIn: {
            /** Customer Name */
            customer_name?: string | null;
            /** Customer Phone */
            customer_phone?: string | null;
            /** Note */
            note?: string | null;
            /** Items */
            items: components["schemas"]["CartLineIn"][];
            /** Expected Total Sen */
            expected_total_sen: number;
        };
        /** OnlineOrderOut */
        OnlineOrderOut: {
            /** Order Number */
            order_number: string;
            /** Order Code */
            order_code: string;
            /** Token */
            token: string;
            /** Status */
            status: string;
            /** Total Sen */
            total_sen: number;
            /** Payment Url */
            payment_url: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** OnlineOrdersIn */
        OnlineOrdersIn: {
            /** Accepting */
            accepting: boolean;
        };
        /** OptionGroupIn */
        OptionGroupIn: {
            /** Name */
            name: string;
            /** Name Ms */
            name_ms?: string | null;
            /**
             * Min Select
             * @default 0
             */
            min_select: number;
            /**
             * Max Select
             * @default 1
             */
            max_select: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** OptionGroupPatch */
        OptionGroupPatch: {
            /** Name */
            name?: string | null;
            /** Name Ms */
            name_ms?: string | null;
            /** Min Select */
            min_select?: number | null;
            /** Max Select */
            max_select?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** OptionIn */
        OptionIn: {
            /** Option Group Id */
            option_group_id: number;
            /** Name */
            name: string;
            /** Name Ms */
            name_ms?: string | null;
            /**
             * Price Delta Sen
             * @default 0
             */
            price_delta_sen: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** OptionPatch */
        OptionPatch: {
            /** Name */
            name?: string | null;
            /** Name Ms */
            name_ms?: string | null;
            /** Price Delta Sen */
            price_delta_sen?: number | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Is Sold Out */
            is_sold_out?: boolean | null;
        };
        /** OrderDetail */
        OrderDetail: {
            /** Id */
            id: number;
            /** Order Number */
            order_number: string;
            /** Order Code */
            order_code: string;
            /** Business Date */
            business_date: string;
            /** Channel */
            channel: string;
            /** Status */
            status: string;
            /** Payment Status */
            payment_status: string;
            /** Customer Name */
            customer_name: string | null;
            /** Note */
            note: string | null;
            /** Subtotal Sen */
            subtotal_sen: number;
            /** Total Sen */
            total_sen: number;
            /** Version */
            version: number;
            /** Auto Closed */
            auto_closed: boolean;
            /** Cancel Reason */
            cancel_reason: string | null;
            /** Created By Name */
            created_by_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Placed At */
            placed_at: string | null;
            /** Ready At */
            ready_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Cancelled At */
            cancelled_at: string | null;
            /** Items */
            items: components["schemas"]["OrderLine"][];
            /** Customer Phone */
            customer_phone: string | null;
            /** Events */
            events: components["schemas"]["OrderEvent"][];
            /** Payments */
            payments: components["schemas"]["OrderPayment"][];
        };
        /** OrderEvent */
        OrderEvent: {
            /** From Status */
            from_status: string | null;
            /** To Status */
            to_status: string;
            /** Actor Type */
            actor_type: string;
            /** Actor Name */
            actor_name: string | null;
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OrderLine */
        OrderLine: {
            /** Id */
            id: number;
            /** Menu Item Id */
            menu_item_id: number;
            /** Item Name */
            item_name: string;
            /** Quantity */
            quantity: number;
            /** Unit Price Sen */
            unit_price_sen: number;
            /** Options Total Sen */
            options_total_sen: number;
            /** Line Total Sen */
            line_total_sen: number;
            /** Note */
            note: string | null;
            /** Options */
            options: components["schemas"]["OrderOption"][];
        };
        /** OrderOption */
        OrderOption: {
            /** Group Name */
            group_name: string;
            /** Option Name */
            option_name: string;
            /** Price Sen */
            price_sen: number;
        };
        /** OrderPayment */
        OrderPayment: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Method */
            method: string;
            /** Amount Sen */
            amount_sen: number;
            /** Status */
            status: string;
            /** Paid At */
            paid_at: string | null;
            /** Recorded By Name */
            recorded_by_name: string | null;
        };
        /** OrderSummary */
        OrderSummary: {
            /** Id */
            id: number;
            /** Order Number */
            order_number: string;
            /** Order Code */
            order_code: string;
            /** Business Date */
            business_date: string;
            /** Channel */
            channel: string;
            /** Status */
            status: string;
            /** Payment Status */
            payment_status: string;
            /** Customer Name */
            customer_name: string | null;
            /** Note */
            note: string | null;
            /** Subtotal Sen */
            subtotal_sen: number;
            /** Total Sen */
            total_sen: number;
            /** Version */
            version: number;
            /** Auto Closed */
            auto_closed: boolean;
            /** Cancel Reason */
            cancel_reason: string | null;
            /** Created By Name */
            created_by_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Placed At */
            placed_at: string | null;
            /** Ready At */
            ready_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Cancelled At */
            cancelled_at: string | null;
            /** Items */
            items: components["schemas"]["OrderLine"][];
        };
        /** PasswordResetIn */
        PasswordResetIn: {
            /** Password */
            password: string;
        };
        /** PaymentLinkOut */
        PaymentLinkOut: {
            /** Payment Url */
            payment_url: string;
        };
        /** Problem */
        Problem: {
            /** Line */
            line: number;
            /** Reason */
            reason: string;
            /** Menu Item Id */
            menu_item_id: number;
            /** Option Id */
            option_id?: number | null;
            /** Option Group Id */
            option_group_id?: number | null;
        };
        /** QuoteIn */
        QuoteIn: {
            /** Items */
            items: components["schemas"]["CartLineIn"][];
        };
        /** QuoteOut */
        QuoteOut: {
            /** Lines */
            lines: components["schemas"]["QuotedLine"][];
            /** Subtotal Sen */
            subtotal_sen: number;
            /** Total Sen */
            total_sen: number;
            /** Problems */
            problems: components["schemas"]["Problem"][];
        };
        /** QuotedLine */
        QuotedLine: {
            /** Menu Item Id */
            menu_item_id: number;
            /** Item Name */
            item_name: string;
            /** Unit Price Sen */
            unit_price_sen: number;
            /** Options Total Sen */
            options_total_sen: number;
            /** Quantity */
            quantity: number;
            /** Line Total Sen */
            line_total_sen: number;
            /** Options */
            options: components["schemas"]["QuotedOption"][];
        };
        /** QuotedOption */
        QuotedOption: {
            /** Option Id */
            option_id: number;
            /** Group Name */
            group_name: string;
            /** Option Name */
            option_name: string;
            /** Price Sen */
            price_sen: number;
        };
        /** RefundIn */
        RefundIn: {
            /** Reason */
            reason: string;
            /**
             * Refund Method
             * @enum {string}
             */
            refund_method: "cash" | "original";
        };
        /** SessionOut */
        SessionOut: {
            user: components["schemas"]["SessionUser"] | null;
            /** Via Pin */
            via_pin: boolean;
            /** Device Registered */
            device_registered: boolean;
            /** Branch Name */
            branch_name: string | null;
        };
        /** SessionUser */
        SessionUser: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Full Name */
            full_name: string;
            /** Role */
            role: string;
            /** Totp Enabled */
            totp_enabled: boolean;
        };
        /** SettingsPatch */
        SettingsPatch: {
            /** Name */
            name?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Prep Minutes */
            prep_minutes?: number | null;
            /** Opening Hours */
            opening_hours?: {
                [key: string]: [
                    string,
                    string
                ][];
            } | null;
        };
        /** ShopOut */
        ShopOut: {
            /** Name */
            name: string;
            /** Is Open */
            is_open: boolean;
            /** Is Accepting Online Orders */
            is_accepting_online_orders: boolean;
            /** Can Order Online */
            can_order_online: boolean;
            /** Prep Minutes */
            prep_minutes: number;
            /** Opening Hours */
            opening_hours: {
                [key: string]: string[][];
            };
            /** Timezone */
            timezone: string;
        };
        /** SoldOutIn */
        SoldOutIn: {
            /** Is Sold Out */
            is_sold_out: boolean;
        };
        /** SortIn */
        SortIn: {
            /**
             * Entity
             * @enum {string}
             */
            entity: "categories" | "items" | "options";
            /** Ids */
            ids: number[];
        };
        /** StaffIn */
        StaffIn: {
            /**
             * Role
             * @default staff
             * @enum {string}
             */
            role: "staff" | "admin";
            /** Username */
            username: string;
            /** Email */
            email?: string | null;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone?: string | null;
            /** Position */
            position?: string | null;
            /** Joined On */
            joined_on?: string | null;
            /** Password */
            password: string;
            /** Pin */
            pin?: string | null;
        };
        /** StaffOut */
        StaffOut: {
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Username */
            username: string;
            /** Email */
            email: string | null;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone: string | null;
            /** Position */
            position: string | null;
            /** Joined On */
            joined_on: string | null;
            /** Left On */
            left_on: string | null;
            /** Is Active */
            is_active: boolean;
            /** Has Pin */
            has_pin: boolean;
            /** Totp Enabled */
            totp_enabled: boolean;
        };
        /** StaffPatch */
        StaffPatch: {
            /** Role */
            role?: ("staff" | "admin") | null;
            /** Email */
            email?: string | null;
            /** Full Name */
            full_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Position */
            position?: string | null;
            /** Joined On */
            joined_on?: string | null;
        };
        /** TotpCodeIn */
        TotpCodeIn: {
            /** Code */
            code: string;
        };
        /** TotpSetupOut */
        TotpSetupOut: {
            /** Secret */
            secret: string;
            /** Otpauth Uri */
            otpauth_uri: string;
        };
        /** TrackingLine */
        TrackingLine: {
            /** Menu Item Id */
            menu_item_id: number;
            /** Item Name */
            item_name: string;
            /** Quantity */
            quantity: number;
            /** Line Total Sen */
            line_total_sen: number;
            /** Note */
            note: string | null;
            /** Option Ids */
            option_ids: number[];
            /** Option Names */
            option_names: string[];
        };
        /** TrackingOut */
        TrackingOut: {
            /** Order Number */
            order_number: string;
            /** Order Code */
            order_code: string;
            /** Status */
            status: string;
            /** Payment Status */
            payment_status: string;
            /** Shop Name */
            shop_name: string;
            /**
             * Detail Hidden
             * @default false
             */
            detail_hidden: boolean;
            /** Customer Name */
            customer_name?: string | null;
            /** Channel */
            channel?: string | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["TrackingLine"][];
            /** Total Sen */
            total_sen?: number | null;
            /** Note */
            note?: string | null;
            /** Prep Minutes */
            prep_minutes?: number | null;
            /** Created At */
            created_at?: string | null;
            /** Placed At */
            placed_at?: string | null;
            /** Ready At */
            ready_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Cancelled At */
            cancelled_at?: string | null;
            /** Cancel Reason */
            cancel_reason?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /**
             * Can Pay
             * @default false
             */
            can_pay: boolean;
            /**
             * Can Cancel
             * @default false
             */
            can_cancel: boolean;
        };
        /** TransitionIn */
        TransitionIn: {
            /**
             * To
             * @enum {string}
             */
            to: "placed" | "preparing" | "ready" | "completed";
            /** Version */
            version: number;
            /** Note */
            note?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** PinIn */
        app__auth__schemas__PinIn: {
            /** User Id */
            user_id: number;
            /** Pin */
            pin: string;
        };
        /** PinIn */
        app__staff__schemas__PinIn: {
            /** Pin */
            pin: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_session_api_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    device_staff_api_v1_auth_device_staff_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceStaff"][];
                };
            };
        };
    };
    pin_api_v1_auth_pin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__auth__schemas__PinIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_device_api_v1_auth_device_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unregister_device_api_v1_auth_device_unregister_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    totp_setup_api_v1_auth_totp_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotpSetupOut"];
                };
            };
        };
    };
    totp_enable_api_v1_auth_totp_enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpCodeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_v1_auth_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shop_api_v1_shop_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopOut"];
                };
            };
        };
    };
    online_orders_api_v1_staff_shop_online_orders_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnlineOrdersIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_v1_admin_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopOut"];
                };
            };
        };
    };
    update_settings_api_v1_admin_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_menu_api_v1_menu_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuOut"];
                };
            };
        };
    };
    item_sold_out_api_v1_staff_menu_items__item_id__sold_out_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SoldOutIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    option_sold_out_api_v1_staff_menu_options__option_id__sold_out_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                option_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SoldOutIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_admin_menu_api_v1_admin_menu_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMenuOut"];
                };
            };
        };
    };
    create_category_api_v1_admin_menu_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCategory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_api_v1_admin_menu_categories__cat_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_api_v1_admin_menu_categories__cat_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cat_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCategory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_api_v1_admin_menu_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_api_v1_admin_menu_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_api_v1_admin_menu_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_item_groups_api_v1_admin_menu_items__item_id__option_groups_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemGroupsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_image_api_v1_admin_menu_items__item_id__image_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_api_v1_admin_menu_items__item_id__image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_group_api_v1_admin_menu_option_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptionGroupIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOptionGroup"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_group_api_v1_admin_menu_option_groups__group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_group_api_v1_admin_menu_option_groups__group_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptionGroupPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOptionGroup"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_option_api_v1_admin_menu_options_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOption"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_option_api_v1_admin_menu_options__option_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                option_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_option_api_v1_admin_menu_options__option_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                option_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptionPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOption"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sort_api_v1_admin_menu_sort_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SortIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_api_v1_orders_quote_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    place_order_api_v1_orders_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnlineOrderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnlineOrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_api_v1_t__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pay_api_v1_t__token__pay_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentLinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_t__token__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    board_api_v1_staff_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummary"][];
                };
            };
        };
    };
    create_api_v1_staff_orders_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CounterOrderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CounterOrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_staff_orders_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_api_v1_staff_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_api_v1_staff_orders__order_id__transition_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_staff_orders__order_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_admin_orders__order_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refund_api_v1_admin_orders__order_id__refund_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefundIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_staff_api_v1_admin_staff_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOut"][];
                };
            };
        };
    };
    create_api_v1_admin_staff_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_v1_admin_staff__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_api_v1_admin_staff__user_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reactivate_api_v1_admin_staff__user_id__reactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_admin_staff__user_id__reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_pin_api_v1_admin_staff__user_id__pin_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__staff__schemas__PinIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    payment_webhook_api_v1_webhooks_payments__provider__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
